updates:
  # Enable version updates for npm
  - package-ecosystem: "pip"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/app"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
